# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: JOB_ROW_DATA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 15 * * 5'

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mensagem inicial
      run : echo Iniciando job em python!
 
  deploy-PRD:
    runs-on: ubuntu-latest
    environment:
      name: PRD
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install requests
          pip install discord_webhook
          pip install boto3
          
      - name: Run script
        env:
          AWS_ACC: ${{secrets.AWS_ACC}}
          AWS_KEY: ${{secrets.AWS_KEY}}
          AUTH_DISCORD_DATA: ${{secrets.AUTH_DISCORD_DATA}}
        run: |
          python tabelas_brutas.py
